[package]
name = "anchor-token"
version = "1.1.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common helpers for other anchor-token specs"
license = "Apache-2.0"
repository = "https://github.com/anchor-protocol/anchor-token-contracts"
homepage = "https://terra.money"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.7.0" } 
cosmwasm-bignumber = "2.1.0"
cosmwasm-std = { version = "0.15.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.15.0", features = ["iterator"] }
terra-cosmwasm = "2.1.0" 
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
 